// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutil

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vitalyshatskikh/crawler-temporal-demo/crawler/parser/internal/domain"
)

// NewMockAdvertsRepository creates a new instance of MockAdvertsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdvertsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdvertsRepository {
	mock := &MockAdvertsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdvertsRepository is an autogenerated mock type for the AdvertsRepository type
type MockAdvertsRepository struct {
	mock.Mock
}

type MockAdvertsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdvertsRepository) EXPECT() *MockAdvertsRepository_Expecter {
	return &MockAdvertsRepository_Expecter{mock: &_m.Mock}
}

// GetDocument provides a mock function for the type MockAdvertsRepository
func (_mock *MockAdvertsRepository) GetDocument(ctx context.Context, sdocID domain.SdocID, sourceID domain.SourceID, docType domain.DocumentType) (domain.Document, error) {
	ret := _mock.Called(ctx, sdocID, sourceID, docType)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 domain.Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SdocID, domain.SourceID, domain.DocumentType) (domain.Document, error)); ok {
		return returnFunc(ctx, sdocID, sourceID, docType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SdocID, domain.SourceID, domain.DocumentType) domain.Document); ok {
		r0 = returnFunc(ctx, sdocID, sourceID, docType)
	} else {
		r0 = ret.Get(0).(domain.Document)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SdocID, domain.SourceID, domain.DocumentType) error); ok {
		r1 = returnFunc(ctx, sdocID, sourceID, docType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdvertsRepository_GetDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocument'
type MockAdvertsRepository_GetDocument_Call struct {
	*mock.Call
}

// GetDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - sdocID domain.SdocID
//   - sourceID domain.SourceID
//   - docType domain.DocumentType
func (_e *MockAdvertsRepository_Expecter) GetDocument(ctx any, sdocID any, sourceID any, docType any) *MockAdvertsRepository_GetDocument_Call {
	return &MockAdvertsRepository_GetDocument_Call{Call: _e.mock.On("GetDocument", ctx, sdocID, sourceID, docType)}
}

func (_c *MockAdvertsRepository_GetDocument_Call) Run(run func(ctx context.Context, sdocID domain.SdocID, sourceID domain.SourceID, docType domain.DocumentType)) *MockAdvertsRepository_GetDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SdocID
		if args[1] != nil {
			arg1 = args[1].(domain.SdocID)
		}
		var arg2 domain.SourceID
		if args[2] != nil {
			arg2 = args[2].(domain.SourceID)
		}
		var arg3 domain.DocumentType
		if args[3] != nil {
			arg3 = args[3].(domain.DocumentType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdvertsRepository_GetDocument_Call) Return(document domain.Document, err error) *MockAdvertsRepository_GetDocument_Call {
	_c.Call.Return(document, err)
	return _c
}

func (_c *MockAdvertsRepository_GetDocument_Call) RunAndReturn(run func(ctx context.Context, sdocID domain.SdocID, sourceID domain.SourceID, docType domain.DocumentType) (domain.Document, error)) *MockAdvertsRepository_GetDocument_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDocument provides a mock function for the type MockAdvertsRepository
func (_mock *MockAdvertsRepository) SaveDocument(ctx context.Context, doc domain.Document) error {
	ret := _mock.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for SaveDocument")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Document) error); ok {
		r0 = returnFunc(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdvertsRepository_SaveDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDocument'
type MockAdvertsRepository_SaveDocument_Call struct {
	*mock.Call
}

// SaveDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - doc domain.Document
func (_e *MockAdvertsRepository_Expecter) SaveDocument(ctx any, doc any) *MockAdvertsRepository_SaveDocument_Call {
	return &MockAdvertsRepository_SaveDocument_Call{Call: _e.mock.On("SaveDocument", ctx, doc)}
}

func (_c *MockAdvertsRepository_SaveDocument_Call) Run(run func(ctx context.Context, doc domain.Document)) *MockAdvertsRepository_SaveDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Document
		if args[1] != nil {
			arg1 = args[1].(domain.Document)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdvertsRepository_SaveDocument_Call) Return(err error) *MockAdvertsRepository_SaveDocument_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdvertsRepository_SaveDocument_Call) RunAndReturn(run func(ctx context.Context, doc domain.Document) error) *MockAdvertsRepository_SaveDocument_Call {
	_c.Call.Return(run)
	return _c
}
