x-common-env: &common_env
  POSTGRES_HOSTS: postgres:5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DATABASE: crawler
  POSTGRES_SSLMODE: disable

services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5534:5432"
    environment:
      POSTGRES_DB: crawler
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 30s
    networks:
      - crawler-network

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    image: crawler-migrate:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment: *common_env
    networks: [crawler-network]
    restart: "no"

  surfer:
    image: crawler-surfer:latest
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment: *common_env
    networks: [crawler-network]
    restart: unless-stopped

  downloader:
    image: crawler-downloader:latest
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment: *common_env
    networks: [crawler-network]
    restart: unless-stopped

networks:
  crawler-network:
    driver: bridge
    name: crawler-network

volumes:
  postgres-data:
