// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutil

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vitalyshatskikh/crawler-temporal-demo/crawler/parser/internal/domain"
)

// NewMockConfigRepository creates a new instance of MockConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigRepository {
	mock := &MockConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigRepository is an autogenerated mock type for the ConfigRepository type
type MockConfigRepository struct {
	mock.Mock
}

type MockConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigRepository) EXPECT() *MockConfigRepository_Expecter {
	return &MockConfigRepository_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function for the type MockConfigRepository
func (_mock *MockConfigRepository) GetConfig(ctx context.Context, sourceID domain.SourceID, docType domain.DocumentType) (domain.ParsingConfig, error) {
	ret := _mock.Called(ctx, sourceID, docType)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 domain.ParsingConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SourceID, domain.DocumentType) (domain.ParsingConfig, error)); ok {
		return returnFunc(ctx, sourceID, docType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SourceID, domain.DocumentType) domain.ParsingConfig); ok {
		r0 = returnFunc(ctx, sourceID, docType)
	} else {
		r0 = ret.Get(0).(domain.ParsingConfig)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SourceID, domain.DocumentType) error); ok {
		r1 = returnFunc(ctx, sourceID, docType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigRepository_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockConfigRepository_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID domain.SourceID
//   - docType domain.DocumentType
func (_e *MockConfigRepository_Expecter) GetConfig(ctx any, sourceID any, docType any) *MockConfigRepository_GetConfig_Call {
	return &MockConfigRepository_GetConfig_Call{Call: _e.mock.On("GetConfig", ctx, sourceID, docType)}
}

func (_c *MockConfigRepository_GetConfig_Call) Run(run func(ctx context.Context, sourceID domain.SourceID, docType domain.DocumentType)) *MockConfigRepository_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SourceID
		if args[1] != nil {
			arg1 = args[1].(domain.SourceID)
		}
		var arg2 domain.DocumentType
		if args[2] != nil {
			arg2 = args[2].(domain.DocumentType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConfigRepository_GetConfig_Call) Return(parsingConfig domain.ParsingConfig, err error) *MockConfigRepository_GetConfig_Call {
	_c.Call.Return(parsingConfig, err)
	return _c
}

func (_c *MockConfigRepository_GetConfig_Call) RunAndReturn(run func(ctx context.Context, sourceID domain.SourceID, docType domain.DocumentType) (domain.ParsingConfig, error)) *MockConfigRepository_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}
