// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutil

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vitalyshatskikh/crawler-temporal-demo/example-site/internal/domain"
)

// NewMockAdvertsRepository creates a new instance of MockAdvertsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdvertsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdvertsRepository {
	mock := &MockAdvertsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdvertsRepository is an autogenerated mock type for the AdvertsRepository type
type MockAdvertsRepository struct {
	mock.Mock
}

type MockAdvertsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdvertsRepository) EXPECT() *MockAdvertsRepository_Expecter {
	return &MockAdvertsRepository_Expecter{mock: &_m.Mock}
}

// DeleteAdvert provides a mock function for the type MockAdvertsRepository
func (_mock *MockAdvertsRepository) DeleteAdvert(ctx context.Context, id domain.AdvertIdentity) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAdvert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AdvertIdentity) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdvertsRepository_DeleteAdvert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAdvert'
type MockAdvertsRepository_DeleteAdvert_Call struct {
	*mock.Call
}

// DeleteAdvert is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.AdvertIdentity
func (_e *MockAdvertsRepository_Expecter) DeleteAdvert(ctx any, id any) *MockAdvertsRepository_DeleteAdvert_Call {
	return &MockAdvertsRepository_DeleteAdvert_Call{Call: _e.mock.On("DeleteAdvert", ctx, id)}
}

func (_c *MockAdvertsRepository_DeleteAdvert_Call) Run(run func(ctx context.Context, id domain.AdvertIdentity)) *MockAdvertsRepository_DeleteAdvert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AdvertIdentity
		if args[1] != nil {
			arg1 = args[1].(domain.AdvertIdentity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdvertsRepository_DeleteAdvert_Call) Return(err error) *MockAdvertsRepository_DeleteAdvert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdvertsRepository_DeleteAdvert_Call) RunAndReturn(run func(ctx context.Context, id domain.AdvertIdentity) error) *MockAdvertsRepository_DeleteAdvert_Call {
	_c.Call.Return(run)
	return _c
}

// GetAdvert provides a mock function for the type MockAdvertsRepository
func (_mock *MockAdvertsRepository) GetAdvert(ctx context.Context, id domain.AdvertIdentity) (domain.Advert, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAdvert")
	}

	var r0 domain.Advert
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AdvertIdentity) (domain.Advert, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AdvertIdentity) domain.Advert); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Advert)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AdvertIdentity) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdvertsRepository_GetAdvert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdvert'
type MockAdvertsRepository_GetAdvert_Call struct {
	*mock.Call
}

// GetAdvert is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.AdvertIdentity
func (_e *MockAdvertsRepository_Expecter) GetAdvert(ctx any, id any) *MockAdvertsRepository_GetAdvert_Call {
	return &MockAdvertsRepository_GetAdvert_Call{Call: _e.mock.On("GetAdvert", ctx, id)}
}

func (_c *MockAdvertsRepository_GetAdvert_Call) Run(run func(ctx context.Context, id domain.AdvertIdentity)) *MockAdvertsRepository_GetAdvert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AdvertIdentity
		if args[1] != nil {
			arg1 = args[1].(domain.AdvertIdentity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdvertsRepository_GetAdvert_Call) Return(advert domain.Advert, err error) *MockAdvertsRepository_GetAdvert_Call {
	_c.Call.Return(advert, err)
	return _c
}

func (_c *MockAdvertsRepository_GetAdvert_Call) RunAndReturn(run func(ctx context.Context, id domain.AdvertIdentity) (domain.Advert, error)) *MockAdvertsRepository_GetAdvert_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAdverts provides a mock function for the type MockAdvertsRepository
func (_mock *MockAdvertsRepository) SearchAdverts(ctx context.Context, params domain.AdvertSearchParams) (domain.AdvertSearchResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SearchAdverts")
	}

	var r0 domain.AdvertSearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AdvertSearchParams) (domain.AdvertSearchResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AdvertSearchParams) domain.AdvertSearchResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(domain.AdvertSearchResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AdvertSearchParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdvertsRepository_SearchAdverts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAdverts'
type MockAdvertsRepository_SearchAdverts_Call struct {
	*mock.Call
}

// SearchAdverts is a helper method to define mock.On call
//   - ctx context.Context
//   - params domain.AdvertSearchParams
func (_e *MockAdvertsRepository_Expecter) SearchAdverts(ctx any, params any) *MockAdvertsRepository_SearchAdverts_Call {
	return &MockAdvertsRepository_SearchAdverts_Call{Call: _e.mock.On("SearchAdverts", ctx, params)}
}

func (_c *MockAdvertsRepository_SearchAdverts_Call) Run(run func(ctx context.Context, params domain.AdvertSearchParams)) *MockAdvertsRepository_SearchAdverts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AdvertSearchParams
		if args[1] != nil {
			arg1 = args[1].(domain.AdvertSearchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdvertsRepository_SearchAdverts_Call) Return(result domain.AdvertSearchResult, err error) *MockAdvertsRepository_SearchAdverts_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockAdvertsRepository_SearchAdverts_Call) RunAndReturn(run func(ctx context.Context, params domain.AdvertSearchParams) (domain.AdvertSearchResult, error)) *MockAdvertsRepository_SearchAdverts_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAdvert provides a mock function for the type MockAdvertsRepository
func (_mock *MockAdvertsRepository) UpsertAdvert(ctx context.Context, advert domain.Advert) (bool, error) {
	ret := _mock.Called(ctx, advert)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAdvert")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Advert) (bool, error)); ok {
		return returnFunc(ctx, advert)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Advert) bool); ok {
		r0 = returnFunc(ctx, advert)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Advert) error); ok {
		r1 = returnFunc(ctx, advert)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdvertsRepository_UpsertAdvert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAdvert'
type MockAdvertsRepository_UpsertAdvert_Call struct {
	*mock.Call
}

// UpsertAdvert is a helper method to define mock.On call
//   - ctx context.Context
//   - advert domain.Advert
func (_e *MockAdvertsRepository_Expecter) UpsertAdvert(ctx any, advert any) *MockAdvertsRepository_UpsertAdvert_Call {
	return &MockAdvertsRepository_UpsertAdvert_Call{Call: _e.mock.On("UpsertAdvert", ctx, advert)}
}

func (_c *MockAdvertsRepository_UpsertAdvert_Call) Run(run func(ctx context.Context, advert domain.Advert)) *MockAdvertsRepository_UpsertAdvert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Advert
		if args[1] != nil {
			arg1 = args[1].(domain.Advert)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdvertsRepository_UpsertAdvert_Call) Return(b bool, err error) *MockAdvertsRepository_UpsertAdvert_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAdvertsRepository_UpsertAdvert_Call) RunAndReturn(run func(ctx context.Context, advert domain.Advert) (bool, error)) *MockAdvertsRepository_UpsertAdvert_Call {
	_c.Call.Return(run)
	return _c
}
